[package]
name = "test_gui_rust_2"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", features = ["wgpu"] }
egui = "0.27.2"
egui_dock = "0.12.0"
futures = "0.3.30"
native-dialog = "0.7.0"
tokio = { version = "1.38.0", features = ["rt", "macros", "sync", "fs", "rt-multi-thread", "time"] }
vec-collections = "0.4.3"
